global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'wordpress'
    metrics_path: '/wp-content/plugins/wordpress-prometheus-exporter/metrics'
    static_configs:
      - targets: ['wordpress:80']